export const SUBMITTALS = [
  {
    id: "run_001",
    projectName: "Meridian Tower — Phase 2",
    projectId: "PRJ-2024-001",
    submittalTitle: "HVAC Variable Air Volume Units",
    specSection: "CSI 23 05 00",
    subcontractor: { name: "Pacific Mechanical Systems", contact: "Dan Ricci", email: "d.ricci@pacificmech.com" },
    dollarAmount: 142500,
    submittedAt: "2025-03-10T09:15:00Z",
    completedAt: "2025-03-10T09:16:32Z",
    processingTimeMs: 92000,
    currentStatus: "approved_internal_progression",
    routingDecision: "auto_route_internal_review",
    executiveDecision: "approve_internal_progression",
    completenessStatus: "complete",
    comparisonStatus: "compliant",
    requiresHumanApproval: true,
    humanApprovalStatus: "approved",
    humanApprovalNote: "Reviewed — product spec matches approved substitution list.",
    agentTrail: [
      { agent: "Intake", status: "accepted", summary: "3 documents received. Envelope validated.", timestamp: "2025-03-10T09:15:02Z" },
      { agent: "Parser", status: "success", summary: "Extracted: Manufacturer — Trane, Model — VAV-2400, Spec — CSI 23 05 00.", timestamp: "2025-03-10T09:15:08Z" },
      { agent: "Requirements", status: "success", summary: "Requirements reconstructed from spec section. 4 mandatory attributes identified.", timestamp: "2025-03-10T09:15:14Z" },
      { agent: "Completeness", status: "complete", summary: "All required documents present: product data sheet, shop drawing, submittal form.", timestamp: "2025-03-10T09:15:20Z" },
      { agent: "Comparison", status: "compliant", summary: "All attributes match requirements. 0 deviations detected.", timestamp: "2025-03-10T09:15:28Z" },
      { agent: "Routing", status: "auto_route_internal_review", summary: "Package complete and compliant. Routed to internal review.", timestamp: "2025-03-10T09:15:34Z" },
      { agent: "Executive", status: "approve_internal_progression", summary: "Final safety check passed. Approved for internal progression.", timestamp: "2025-03-10T09:16:32Z" },
    ],
    communications: [
      { id: "msg_001a", direction: "agent_out", text: "Your submittal for HVAC Variable Air Volume Units (CSI 23 05 00) has been received and is under review.", timestamp: "2025-03-10T09:15:05Z", agent: "Intake", humanControlled: false },
      { id: "msg_001b", direction: "agent_out", text: "Review complete. Your package is compliant and has been approved for internal progression. No further action required.", timestamp: "2025-03-10T09:16:35Z", agent: "Executive", humanControlled: false },
    ],
  },
  {
    id: "run_002",
    projectName: "Meridian Tower — Phase 2",
    projectId: "PRJ-2024-001",
    submittalTitle: "Electrical Switchgear Panel — 480V",
    specSection: "CSI 26 24 13",
    subcontractor: { name: "Volta Electrical Contractors", contact: "Maria Santos", email: "m.santos@voltaec.com" },
    dollarAmount: 87300,
    submittedAt: "2025-03-11T11:02:00Z",
    completedAt: "2025-03-11T11:03:18Z",
    processingTimeMs: 78000,
    currentStatus: "returned_to_subcontractor",
    routingDecision: "return_to_subcontractor",
    executiveDecision: "return_to_subcontractor",
    completenessStatus: "incomplete",
    comparisonStatus: null,
    requiresHumanApproval: false,
    humanApprovalStatus: null,
    humanApprovalNote: null,
    agentTrail: [
      { agent: "Intake", status: "accepted_with_warnings", summary: "2 documents received. One document flagged as low-text scan.", timestamp: "2025-03-11T11:02:05Z" },
      { agent: "Parser", status: "success", summary: "Extracted: Manufacturer — Eaton, Model — PRL3A, Spec — CSI 26 24 13.", timestamp: "2025-03-11T11:02:12Z" },
      { agent: "Requirements", status: "success", summary: "3 mandatory documents required: product data, shop drawing, short circuit study.", timestamp: "2025-03-11T11:02:18Z" },
      { agent: "Completeness", status: "incomplete", summary: "Missing: short circuit study. Package cannot proceed.", timestamp: "2025-03-11T11:02:26Z" },
      { agent: "Routing", status: "return_to_subcontractor", summary: "Incomplete package. Returned to subcontractor for resubmission.", timestamp: "2025-03-11T11:02:34Z" },
      { agent: "Executive", status: "return_to_subcontractor", summary: "Confirmed: package returned. Awaiting resubmission with short circuit study.", timestamp: "2025-03-11T11:03:18Z" },
    ],
    communications: [
      { id: "msg_002a", direction: "agent_out", text: "Your submittal for Electrical Switchgear Panel — 480V has been received.", timestamp: "2025-03-11T11:02:07Z", agent: "Intake", humanControlled: false, sentiment: null },
      { id: "msg_002b", direction: "agent_out", text: "Review identified a missing required document: Short Circuit Study. Please resubmit with this document included.", timestamp: "2025-03-11T11:03:20Z", agent: "Executive", humanControlled: false, sentiment: null },
      { id: "msg_002c", direction: "sub_in", text: "Understood. We'll have the short circuit study ready by end of week and will resubmit.", timestamp: "2025-03-11T14:45:00Z", agent: null, humanControlled: false, sentiment: { label: "neutral", score: 20, flags: [] } },
      { id: "msg_002d", direction: "sub_in", text: "Still waiting on a confirmation that our resubmission was received. It has been 3 days. We need this cleared before Friday or our install crew is sitting idle.", timestamp: "2025-03-14T09:15:00Z", agent: null, humanControlled: false, sentiment: { label: "frustrated", score: 72, flags: ["timeline_pressure", "idle_crew"] } },
    ],
  },
  {
    id: "run_003",
    projectName: "Harbor View Residences",
    projectId: "PRJ-2024-003",
    submittalTitle: "Structural Steel — Wide Flange Beams",
    specSection: "CSI 05 12 00",
    subcontractor: { name: "Ironclad Fabricators", contact: "Steve Malone", email: "smalone@ironclad.com" },
    dollarAmount: 318000,
    submittedAt: "2025-03-11T14:20:00Z",
    completedAt: "2025-03-11T14:21:44Z",
    processingTimeMs: 104000,
    currentStatus: "escalated_to_human",
    routingDecision: "human_exception_queue",
    executiveDecision: "escalate_to_human",
    completenessStatus: "complete",
    comparisonStatus: "deviation_detected",
    requiresHumanApproval: true,
    humanApprovalStatus: "pending",
    humanApprovalNote: null,
    agentTrail: [
      { agent: "Intake", status: "accepted", summary: "4 documents received. All documents extracted successfully.", timestamp: "2025-03-11T14:20:06Z" },
      { agent: "Parser", status: "success", summary: "Extracted: Manufacturer — Nucor, Model — W14x82, Spec — CSI 05 12 00. Deviation detected: Grade 50 substituted for Grade 60.", timestamp: "2025-03-11T14:20:14Z" },
      { agent: "Requirements", status: "success", summary: "Requirements reconstructed. Grade 60 steel required per spec.", timestamp: "2025-03-11T14:20:22Z" },
      { agent: "Completeness", status: "complete", summary: "All 4 required documents present.", timestamp: "2025-03-11T14:20:30Z" },
      { agent: "Comparison", status: "deviation_detected", summary: "Steel grade mismatch: required Grade 60, submitted Grade 50. Substitution letter present.", timestamp: "2025-03-11T14:20:40Z" },
      { agent: "Routing", status: "human_exception_queue", summary: "Deviation detected. Escalated to human exception queue for engineer review.", timestamp: "2025-03-11T14:20:50Z" },
      { agent: "Executive", status: "escalate_to_human", summary: "Deviation requires structural engineer sign-off. Escalated.", timestamp: "2025-03-11T14:21:44Z" },
    ],
    communications: [
      { id: "msg_003a", direction: "agent_out", text: "Your submittal for Structural Steel — Wide Flange Beams has been received and is under review.", timestamp: "2025-03-11T14:20:08Z", agent: "Intake", humanControlled: false, sentiment: null },
      { id: "msg_003b", direction: "agent_out", text: "A deviation has been detected in your submittal: steel grade Grade 50 does not match the specified Grade 60. Your package has been escalated for engineer review. You will be contacted within 2 business days.", timestamp: "2025-03-11T14:21:46Z", agent: "Executive", humanControlled: false, sentiment: null },
      { id: "msg_003c", direction: "sub_in", text: "This is completely unacceptable. Grade 50 is a standard industry substitution and we included a full substitution letter. We have been waiting 3 days with zero response. Our fabrication schedule cannot slip — we have steel in the yard ready to cut. Someone needs to make a decision TODAY.", timestamp: "2025-03-14T07:45:00Z", agent: null, humanControlled: false, sentiment: { label: "critical", score: 94, flags: ["escalation_demand", "schedule_impact", "material_ready", "urgent"] } },
    ],
  },
  {
    id: "run_004",
    projectName: "Westside Community Center",
    projectId: "PRJ-2024-005",
    submittalTitle: "Fire Suppression Sprinkler Heads",
    specSection: "CSI 21 13 13",
    subcontractor: { name: "Summit Fire Protection", contact: "Amy Chen", email: "a.chen@summitfire.com" },
    dollarAmount: 29400,
    submittedAt: "2025-03-12T08:30:00Z",
    completedAt: "2025-03-12T08:31:10Z",
    processingTimeMs: 70000,
    currentStatus: "approved_internal_progression",
    routingDecision: "auto_route_internal_review",
    executiveDecision: "approve_internal_progression",
    completenessStatus: "complete",
    comparisonStatus: "compliant",
    requiresHumanApproval: false,
    humanApprovalStatus: null,
    humanApprovalNote: null,
    agentTrail: [
      { agent: "Intake", status: "accepted", summary: "2 documents received. All documents extracted.", timestamp: "2025-03-12T08:30:04Z" },
      { agent: "Parser", status: "success", summary: "Extracted: Manufacturer — Viking, Model — VK102, Spec — CSI 21 13 13.", timestamp: "2025-03-12T08:30:10Z" },
      { agent: "Requirements", status: "success", summary: "Requirements reconstructed. 2 mandatory documents identified.", timestamp: "2025-03-12T08:30:16Z" },
      { agent: "Completeness", status: "complete", summary: "All required documents present.", timestamp: "2025-03-12T08:30:22Z" },
      { agent: "Comparison", status: "compliant", summary: "All attributes match. 0 deviations.", timestamp: "2025-03-12T08:30:30Z" },
      { agent: "Routing", status: "auto_route_internal_review", summary: "Complete and compliant. Auto-routed.", timestamp: "2025-03-12T08:30:38Z" },
      { agent: "Executive", status: "approve_internal_progression", summary: "Approved.", timestamp: "2025-03-12T08:31:10Z" },
    ],
    communications: [
      { id: "msg_004a", direction: "agent_out", text: "Your submittal for Fire Suppression Sprinkler Heads has been received and is under review.", timestamp: "2025-03-12T08:30:06Z", agent: "Intake", humanControlled: false },
      { id: "msg_004b", direction: "agent_out", text: "Review complete. Your package is compliant and approved for internal progression.", timestamp: "2025-03-12T08:31:12Z", agent: "Executive", humanControlled: false },
    ],
  },
  {
    id: "run_005",
    projectName: "Harbor View Residences",
    projectId: "PRJ-2024-003",
    submittalTitle: "Elevator Cab Finishes — Stainless Steel",
    specSection: "CSI 14 21 00",
    subcontractor: { name: "Apex Elevator Solutions", contact: "Kevin Park", email: "k.park@apexelevator.com" },
    dollarAmount: 205000,
    submittedAt: "2025-03-12T10:15:00Z",
    completedAt: null,
    processingTimeMs: null,
    currentStatus: "pending_human_approval",
    routingDecision: null,
    executiveDecision: null,
    completenessStatus: null,
    comparisonStatus: null,
    requiresHumanApproval: true,
    humanApprovalStatus: "pending",
    humanApprovalNote: null,
    agentTrail: [
      { agent: "Intake", status: "accepted", summary: "3 documents received. Flagged for human approval due to dollar threshold ($205,000).", timestamp: "2025-03-12T10:15:06Z" },
    ],
    communications: [
      { id: "msg_005a", direction: "agent_out", text: "Your submittal for Elevator Cab Finishes — Stainless Steel has been received. Due to the contract value, this submittal requires manager approval before processing. We will notify you once reviewed.", timestamp: "2025-03-12T10:15:08Z", agent: "Intake", humanControlled: false },
    ],
  },
  {
    id: "run_006",
    projectName: "Northgate Office Park",
    projectId: "PRJ-2024-007",
    submittalTitle: "Roofing Membrane — TPO 60mil",
    specSection: "CSI 07 54 19",
    subcontractor: { name: "Eagle Roofing Systems", contact: "Bob Tran", email: "b.tran@eagleroofing.com" },
    dollarAmount: 94700,
    submittedAt: "2025-03-12T13:45:00Z",
    completedAt: "2025-03-12T13:46:30Z",
    processingTimeMs: 90000,
    currentStatus: "escalated_to_human",
    routingDecision: "human_exception_queue",
    executiveDecision: "escalate_to_human",
    completenessStatus: "needs_human_review",
    comparisonStatus: "unclear",
    requiresHumanApproval: false,
    humanApprovalStatus: null,
    humanApprovalNote: null,
    agentTrail: [
      { agent: "Intake", status: "accepted_with_warnings", summary: "2 documents received. One PDF flagged as low-text scanned document.", timestamp: "2025-03-12T13:45:07Z" },
      { agent: "Parser", status: "success", summary: "Partial extraction. Product type and spec section identified. Manufacturer field unclear from scan.", timestamp: "2025-03-12T13:45:14Z" },
      { agent: "Requirements", status: "success", summary: "Requirements reconstructed.", timestamp: "2025-03-12T13:45:20Z" },
      { agent: "Completeness", status: "needs_human_review", summary: "Document present but content unreadable in key sections. Human review required.", timestamp: "2025-03-12T13:45:28Z" },
      { agent: "Comparison", status: "unclear", summary: "Cannot verify manufacturer or model — scan quality insufficient.", timestamp: "2025-03-12T13:45:38Z" },
      { agent: "Routing", status: "human_exception_queue", summary: "Ambiguous documents. Escalated for human review.", timestamp: "2025-03-12T13:45:48Z" },
      { agent: "Executive", status: "escalate_to_human", summary: "Scan quality prevents automated review. Human review required.", timestamp: "2025-03-12T13:46:30Z" },
    ],
    communications: [
      { id: "msg_006a", direction: "agent_out", text: "Your submittal for Roofing Membrane — TPO 60mil has been received.", timestamp: "2025-03-12T13:45:09Z", agent: "Intake", humanControlled: false, sentiment: null },
      { id: "msg_006b", direction: "agent_out", text: "We were unable to process your submittal automatically due to poor scan quality on one of the documents. A reviewer has been assigned and will follow up within 1 business day.", timestamp: "2025-03-12T13:46:32Z", agent: "Executive", humanControlled: false, sentiment: null },
      { id: "msg_006c", direction: "sub_in", text: "Poor scan quality? We submitted the exact same PDFs we always send. If your system can't read a standard PDF that's not our problem. How long is this going to take? We're supposed to start install next week.", sentiment: { label: "frustrated", score: 68, flags: ["quality_dispute", "timeline_pressure"] }, timestamp: "2025-03-13T08:20:00Z", agent: null, humanControlled: false },
      { id: "msg_006d", direction: "sub_in", text: "It has now been over 24 hours and we still have no update. This is holding up our crew scheduling. We need a status by end of day.", timestamp: "2025-03-14T10:05:00Z", agent: null, humanControlled: false, sentiment: { label: "frustrated", score: 75, flags: ["no_response", "crew_scheduling", "deadline"] } },
    ],
  },
  {
    id: "run_007",
    projectName: "Westside Community Center",
    projectId: "PRJ-2024-005",
    submittalTitle: "Acoustic Ceiling Tiles — 2x4 Grid",
    specSection: "CSI 09 51 13",
    subcontractor: { name: "Interior Finishes Co.", contact: "Lisa Huang", email: "l.huang@intfinishes.com" },
    dollarAmount: 38200,
    submittedAt: "2025-03-13T09:00:00Z",
    completedAt: "2025-03-13T09:01:05Z",
    processingTimeMs: 65000,
    currentStatus: "approved_internal_progression",
    routingDecision: "auto_route_internal_review",
    executiveDecision: "approve_internal_progression",
    completenessStatus: "complete",
    comparisonStatus: "compliant",
    requiresHumanApproval: false,
    humanApprovalStatus: null,
    humanApprovalNote: null,
    agentTrail: [
      { agent: "Intake", status: "accepted", summary: "2 documents received.", timestamp: "2025-03-13T09:00:04Z" },
      { agent: "Parser", status: "success", summary: "Extracted: Manufacturer — Armstrong, Model — Ultima 1774, Spec — CSI 09 51 13.", timestamp: "2025-03-13T09:00:10Z" },
      { agent: "Requirements", status: "success", summary: "Requirements reconstructed.", timestamp: "2025-03-13T09:00:16Z" },
      { agent: "Completeness", status: "complete", summary: "All documents present.", timestamp: "2025-03-13T09:00:22Z" },
      { agent: "Comparison", status: "compliant", summary: "All attributes match.", timestamp: "2025-03-13T09:00:30Z" },
      { agent: "Routing", status: "auto_route_internal_review", summary: "Auto-routed to internal review.", timestamp: "2025-03-13T09:00:38Z" },
      { agent: "Executive", status: "approve_internal_progression", summary: "Approved.", timestamp: "2025-03-13T09:01:05Z" },
    ],
    communications: [
      { id: "msg_007a", direction: "agent_out", text: "Your submittal for Acoustic Ceiling Tiles — 2x4 Grid has been received and is under review.", timestamp: "2025-03-13T09:00:06Z", agent: "Intake", humanControlled: false },
      { id: "msg_007b", direction: "agent_out", text: "Review complete. Package approved for internal progression.", timestamp: "2025-03-13T09:01:07Z", agent: "Executive", humanControlled: false },
    ],
  },
  {
    id: "run_008",
    projectName: "Northgate Office Park",
    projectId: "PRJ-2024-007",
    submittalTitle: "Glazing System — Curtain Wall Units",
    specSection: "CSI 08 44 13",
    subcontractor: { name: "ClearVue Glazing Ltd.", contact: "Tom Okafor", email: "t.okafor@clearvue.com" },
    dollarAmount: 512000,
    submittedAt: "2025-03-13T11:30:00Z",
    completedAt: null,
    processingTimeMs: null,
    currentStatus: "pending_human_approval",
    routingDecision: null,
    executiveDecision: null,
    completenessStatus: null,
    comparisonStatus: null,
    requiresHumanApproval: true,
    humanApprovalStatus: "pending",
    humanApprovalNote: null,
    agentTrail: [
      { agent: "Intake", status: "accepted", summary: "5 documents received. Flagged for human approval due to dollar threshold ($512,000).", timestamp: "2025-03-13T11:30:07Z" },
    ],
    communications: [
      { id: "msg_008a", direction: "agent_out", text: "Your submittal for Glazing System — Curtain Wall Units has been received. Due to the contract value, this submittal requires manager approval before processing. We will notify you once reviewed.", timestamp: "2025-03-13T11:30:09Z", agent: "Intake", humanControlled: false },
    ],
  },
  {
    id: "run_009",
    projectName: "Meridian Tower — Phase 2",
    projectId: "PRJ-2024-001",
    submittalTitle: "Plumbing Fixtures — Commercial Restrooms",
    specSection: "CSI 22 40 00",
    subcontractor: { name: "Pacific Mechanical Systems", contact: "Dan Ricci", email: "d.ricci@pacificmech.com" },
    dollarAmount: 61800,
    submittedAt: "2025-03-13T14:00:00Z",
    completedAt: "2025-03-13T14:01:25Z",
    processingTimeMs: 85000,
    currentStatus: "returned_to_subcontractor",
    routingDecision: "return_to_subcontractor",
    executiveDecision: "return_to_subcontractor",
    completenessStatus: "incomplete",
    comparisonStatus: null,
    requiresHumanApproval: false,
    humanApprovalStatus: null,
    humanApprovalNote: null,
    agentTrail: [
      { agent: "Intake", status: "accepted", summary: "2 documents received.", timestamp: "2025-03-13T14:00:05Z" },
      { agent: "Parser", status: "success", summary: "Extracted: Manufacturer — Kohler, Model — K-4326, Spec — CSI 22 40 00.", timestamp: "2025-03-13T14:00:12Z" },
      { agent: "Requirements", status: "success", summary: "3 mandatory documents required: product data, flush valve spec, ADA compliance cert.", timestamp: "2025-03-13T14:00:18Z" },
      { agent: "Completeness", status: "incomplete", summary: "Missing: ADA compliance certificate.", timestamp: "2025-03-13T14:00:26Z" },
      { agent: "Routing", status: "return_to_subcontractor", summary: "Incomplete. Returned.", timestamp: "2025-03-13T14:00:34Z" },
      { agent: "Executive", status: "return_to_subcontractor", summary: "Returned to subcontractor. Awaiting ADA cert.", timestamp: "2025-03-13T14:01:25Z" },
    ],
    communications: [
      { id: "msg_009a", direction: "agent_out", text: "Your submittal for Plumbing Fixtures — Commercial Restrooms has been received.", timestamp: "2025-03-13T14:00:07Z", agent: "Intake", humanControlled: false },
      { id: "msg_009b", direction: "agent_out", text: "Review identified a missing required document: ADA Compliance Certificate. Please resubmit with this document included.", timestamp: "2025-03-13T14:01:27Z", agent: "Executive", humanControlled: false },
      { id: "msg_009c", direction: "sub_in", text: "We'll pull the cert from Kohler and resubmit by tomorrow morning.", timestamp: "2025-03-13T15:10:00Z", agent: null, humanControlled: false, sentiment: { label: "neutral", score: 15, flags: [] } },
    ],
  },
  {
    id: "run_010",
    projectName: "Harbor View Residences",
    projectId: "PRJ-2024-003",
    submittalTitle: "Exterior Paint System — Low-VOC",
    specSection: "CSI 09 91 00",
    subcontractor: { name: "ColorRight Painting", contact: "Nina Patel", email: "n.patel@colorright.com" },
    dollarAmount: 44100,
    submittedAt: "2025-03-14T08:00:00Z",
    completedAt: "2025-03-14T08:01:00Z",
    processingTimeMs: 60000,
    currentStatus: "approved_internal_progression",
    routingDecision: "auto_route_internal_review",
    executiveDecision: "approve_internal_progression",
    completenessStatus: "complete",
    comparisonStatus: "compliant",
    requiresHumanApproval: false,
    humanApprovalStatus: null,
    humanApprovalNote: null,
    agentTrail: [
      { agent: "Intake", status: "accepted", summary: "2 documents received.", timestamp: "2025-03-14T08:00:04Z" },
      { agent: "Parser", status: "success", summary: "Extracted: Manufacturer — Sherwin-Williams, Model — Emerald Exterior, Spec — CSI 09 91 00.", timestamp: "2025-03-14T08:00:10Z" },
      { agent: "Requirements", status: "success", summary: "Requirements reconstructed.", timestamp: "2025-03-14T08:00:16Z" },
      { agent: "Completeness", status: "complete", summary: "All documents present.", timestamp: "2025-03-14T08:00:22Z" },
      { agent: "Comparison", status: "compliant", summary: "All attributes match.", timestamp: "2025-03-14T08:00:30Z" },
      { agent: "Routing", status: "auto_route_internal_review", summary: "Auto-routed.", timestamp: "2025-03-14T08:00:38Z" },
      { agent: "Executive", status: "approve_internal_progression", summary: "Approved.", timestamp: "2025-03-14T08:01:00Z" },
    ],
    communications: [
      { id: "msg_010a", direction: "agent_out", text: "Your submittal for Exterior Paint System — Low-VOC has been received and is under review.", timestamp: "2025-03-14T08:00:06Z", agent: "Intake", humanControlled: false },
      { id: "msg_010b", direction: "agent_out", text: "Review complete. Package approved for internal progression.", timestamp: "2025-03-14T08:01:02Z", agent: "Executive", humanControlled: false },
    ],
  },
];

export const PROJECTS = [
  { id: "PRJ-2024-001", name: "Meridian Tower — Phase 2", client: "Meridian Development Group" },
  { id: "PRJ-2024-003", name: "Harbor View Residences", client: "Harbor Bay LLC" },
  { id: "PRJ-2024-005", name: "Westside Community Center", client: "City of Westside" },
  { id: "PRJ-2024-007", name: "Northgate Office Park", client: "Northgate Properties" },
];

// Derived stats for dashboard
export function getDashboardStats() {
  const thisWeek = SUBMITTALS.filter(s => new Date(s.submittedAt) >= new Date("2025-03-10T00:00:00Z"));
  const completed = SUBMITTALS.filter(s => s.completedAt);
  const approved = completed.filter(s => s.executiveDecision === "approve_internal_progression");
  const pendingApproval = SUBMITTALS.filter(s => s.humanApprovalStatus === "pending");
  const avgMs = completed.filter(s => s.processingTimeMs).reduce((a, s) => a + s.processingTimeMs, 0) / completed.filter(s => s.processingTimeMs).length;

  return {
    totalThisWeek: thisWeek.length,
    approvalRate: Math.round((approved.length / completed.length) * 100),
    pendingApproval: pendingApproval.length,
    avgProcessingSeconds: Math.round(avgMs / 1000),
  };
}

export function getWeeklyChartData() {
  return [
    { day: "Mon 3/10", approved: 1, returned: 0, escalated: 0 },
    { day: "Tue 3/11", approved: 0, returned: 1, escalated: 1 },
    { day: "Wed 3/12", approved: 1, returned: 0, escalated: 1 },
    { day: "Thu 3/13", approved: 2, returned: 1, escalated: 0 },
    { day: "Fri 3/14", approved: 1, returned: 0, escalated: 0 },
  ];
}

export function getSentimentAlerts() {
  const alerts = [];
  for (const s of SUBMITTALS) {
    const subMessages = s.communications.filter(m => m.direction === "sub_in" && m.sentiment);
    if (subMessages.length === 0) continue;
    const topMsg = subMessages.reduce((a, b) => (b.sentiment.score > a.sentiment.score ? b : a));
    if (topMsg.sentiment.score >= 60) {
      alerts.push({
        submittalId: s.id,
        submittalTitle: s.submittalTitle,
        projectName: s.projectName,
        subcontractor: s.subcontractor,
        sentiment: topMsg.sentiment,
        triggerMessage: topMsg.text,
        timestamp: topMsg.timestamp,
      });
    }
  }
  return alerts.sort((a, b) => b.sentiment.score - a.sentiment.score);
}

export function getRoutingBreakdown() {
  const approved = SUBMITTALS.filter(s => s.executiveDecision === "approve_internal_progression").length;
  const returned = SUBMITTALS.filter(s => s.executiveDecision === "return_to_subcontractor").length;
  const escalated = SUBMITTALS.filter(s => s.executiveDecision === "escalate_to_human").length;
  const pending = SUBMITTALS.filter(s => !s.executiveDecision).length;
  return [
    { name: "Approved", value: approved, color: "#16a34a" },
    { name: "Returned", value: returned, color: "#d97706" },
    { name: "Escalated", value: escalated, color: "#dc2626" },
    { name: "Pending", value: pending, color: "#6366f1" },
  ];
}
